version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
