from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import ants

from kwneuro.cache import cacheable
from kwneuro.resource import InMemoryVolumeResource, VolumeResource
from kwneuro.util import PathLike, normalize_path

if TYPE_CHECKING:
    from kwneuro.dwi import Dwi
    from kwneuro.structural import StructuralImage

TRANSFORM_MANIFEST = "transform.json"


@dataclass()
class TransformResource:
    """A wrapper for ANTs registration results that simplifies viewing and
    applying transforms. While the underlying transform files are always
    stored on-disk, they remain in a temporary directory until explicitly
    persisted via the save() method."""

    # Raw paths to ants output files
    _ants_fwd_paths: list[str]
    _ants_inv_paths: list[str]

    # Store the actual objects if they are already loaded
    _matrices: list[ants.ANTsTransform] | None = None
    _warps: list[InMemoryVolumeResource] | None = None

    @property
    def matrices(self) -> list[ants.ANTsTransform]:
        """Returns the affine transform if it exists."""
        if self._matrices is None:
            # Find the .mat file in paths and load it
            mat_paths = [p for p in self._ants_fwd_paths if p.endswith(".mat")]
            self._matrices = [ants.core.read_transform(p) for p in mat_paths]
        return self._matrices

    @property
    def warp_fields(self) -> list[InMemoryVolumeResource]:
        """Returns the non-linear displacement field if it exists."""

        if self._warps is None:
            # Get all warp files (typically .nii)
            warp_paths = [p for p in self._ants_fwd_paths if ".nii" in p]

            warp_volumes = []
            for p in warp_paths:
                ants_img = ants.image_read(p)
                warp_volumes.append(InMemoryVolumeResource.from_ants_image(ants_img))
            self._warps = warp_volumes
        return self._warps

    @staticmethod
    def initialize_from_ants(ants_result: dict[str, list[str]]) -> TransformResource:
        """Initializes a TransformResource from an ANTs registration result by
        wrapping references to the temporary transform files generated by ANTs."""

        ants_fwdtransforms = ants_result["fwdtransforms"]

        return TransformResource(
            _ants_fwd_paths=ants_fwdtransforms,
            _ants_inv_paths=ants_result["invtransforms"],
        )

    def apply(
        self,
        fixed: VolumeResource,
        moving: VolumeResource,
        invert: bool = False,
        interpolation: str = "linear",
    ) -> InMemoryVolumeResource:
        """Wrapper around ants.apply_transforms using this result."""

        fixed = fixed.load()
        moving = moving.load()

        ants_fixed = fixed.to_ants_image()
        ants_moving = moving.to_ants_image()

        transforms = self._ants_inv_paths if invert else self._ants_fwd_paths

        # Ants does not pre-invert the .mat files
        # so we need to explicitly specify that it needs to be inverted.
        # This is done in ANTs by default when the inv transform list is used but
        # we specify it here for clarity.
        if invert:
            whichtoinvert = [p.endswith(".mat") for p in transforms]
        else:
            whichtoinvert = [False] * len(transforms)

        warpedmovout = ants.apply_transforms(
            fixed=ants_fixed,
            moving=ants_moving,
            transformlist=transforms,
            whichtoinvert=whichtoinvert,
            interpolator=interpolation,
        )

        return InMemoryVolumeResource.from_ants_image(warpedmovout)

    @classmethod
    def _cache_files(cls, step_name: str) -> list[str]:
        return [f"{step_name}_transform/{TRANSFORM_MANIFEST}"]

    def _cache_save(self, cache_dir: Path, step_name: str) -> None:
        self.save(cache_dir / f"{step_name}_transform")

    @classmethod
    def _cache_load(cls, cache_dir: Path, step_name: str) -> TransformResource:
        return cls.load(cache_dir / f"{step_name}_transform")

    @classmethod
    def load(cls, output_dir: PathLike) -> TransformResource:
        """Load a saved transform directory produced by :meth:`save`."""
        path = normalize_path(output_dir)
        manifest_path = path / TRANSFORM_MANIFEST
        manifest = json.loads(manifest_path.read_text())

        fwd = manifest["fwd"]
        inv = manifest["inv"]
        if not isinstance(fwd, list) or not all(isinstance(p, str) for p in fwd):
            msg = f"Invalid transform manifest: {manifest_path}"
            raise ValueError(msg)
        if not isinstance(inv, list) or not all(isinstance(p, str) for p in inv):
            msg = f"Invalid transform manifest: {manifest_path}"
            raise ValueError(msg)

        return cls(
            _ants_fwd_paths=[str(_resolve_manifest_path(path, p)) for p in fwd],
            _ants_inv_paths=[str(_resolve_manifest_path(path, p)) for p in inv],
        )

    def save(self, output_dir: PathLike) -> TransformResource:
        """Copies the underlying ANTs transformation files to a permanent directory
        and returns a new TransformResource pointing to the saved locations"""

        path = normalize_path(output_dir)
        path.mkdir(parents=True, exist_ok=True)

        # Files get saved with default temp names from ANTs
        copied_files = {}
        saved_fwd_paths = []
        manifest_fwd_paths = []
        for p in self._ants_fwd_paths:
            if p not in copied_files:
                dest = path / Path(p).name
                shutil.copy(p, dest)
                copied_files[p] = dest
            saved_fwd_paths.append(str(copied_files[p]))
            manifest_fwd_paths.append(copied_files[p].relative_to(path).as_posix())

        saved_inv_paths = []
        manifest_inv_paths = []
        for p in self._ants_inv_paths:
            if p not in copied_files:
                dest = path / Path(p).name
                shutil.copy(p, dest)
                copied_files[p] = dest
            saved_inv_paths.append(str(copied_files[p]))
            manifest_inv_paths.append(copied_files[p].relative_to(path).as_posix())

        manifest = {"fwd": manifest_fwd_paths, "inv": manifest_inv_paths}
        (path / TRANSFORM_MANIFEST).write_text(json.dumps(manifest, indent=2))

        return TransformResource(
            _ants_fwd_paths=saved_fwd_paths,
            _ants_inv_paths=saved_inv_paths,
        )


def _resolve_manifest_path(transform_dir: Path, relative_path: str) -> Path:
    path = Path(relative_path)
    if path.is_absolute():
        msg = "Transform manifest paths must be relative."
        raise ValueError(msg)

    candidate = (transform_dir / path).resolve()
    if not candidate.is_relative_to(transform_dir):
        msg = "Transform manifest paths must stay within the transform directory."
        raise ValueError(msg)
    return candidate


def register_volumes(
    fixed: VolumeResource,
    moving: VolumeResource,
    type_of_transform: str = "SyN",
    mask: VolumeResource | None = None,
    moving_mask: VolumeResource | None = None,
) -> tuple[InMemoryVolumeResource, TransformResource]:
    """
    Registers a moving volume to a fixed reference volume using ANTs.

    Args:
        fixed: The reference volume.
        moving: The volume to be warped.
        type_of_transform: The transformation model (e.g., "SyN", "Rigid"). The full list of
            supported transforms can be found in the ANTs documentation.
        mask: Optional mask for the fixed image space.
        moving_mask: Optional mask for the moving image space.

    Returns:
        A tuple containing the registered volume and the transform object.

    """
    fixed = fixed.load()
    moving = moving.load()

    # Check input volume
    if fixed.get_array().ndim > 3 or moving.get_array().ndim > 3:
        error_message = "Input volume dimensions must be 2D or 3D."
        raise ValueError(error_message)

    ants_fixed = fixed.to_ants_image()
    ants_moving = moving.to_ants_image()

    # Convert masks to ants images if provided
    ants_mask = mask.load().to_ants_image() if mask is not None else None
    ants_moving_mask = (
        moving_mask.load().to_ants_image() if moving_mask is not None else None
    )

    # Check that the mask dimensions match the fixed/moving images
    if ants_mask is not None and (ants_mask.shape != ants_fixed.shape):
        error_message = "Fixed mask dimensions do not match fixed image dimensions."
        raise ValueError(error_message)
    if ants_moving_mask is not None and (ants_moving_mask.shape != ants_moving.shape):
        error_message = "Moving mask dimensions do not match moving image dimensions."
        raise ValueError(error_message)

    ants_result = ants.registration(
        fixed=ants_fixed,
        moving=ants_moving,
        mask=ants_mask,
        moving_mask=ants_moving_mask,
        type_of_transform=type_of_transform,
    )

    warpedmovout = InMemoryVolumeResource.from_ants_image(ants_result["warpedmovout"])

    transform = TransformResource.initialize_from_ants(ants_result)

    return (warpedmovout, transform)


def register_volumes_multimetric(
    fixed: dict[str, VolumeResource],
    moving: dict[str, VolumeResource],
    weights: dict[str, float] | None = None,
    mask: VolumeResource | None = None,
    moving_mask: VolumeResource | None = None,
) -> tuple[dict[str, InMemoryVolumeResource], TransformResource]:
    """
    Registers multiple moving volumes to a fixed reference using multi-metric ANTs.

    The primary modality (first key) drives an initial Affine stage; all modalities
    then contribute to a SyNOnly deformable stage via ``multivariate_extras``.
    Requires at least two modalities; use :func:`register_volumes` for
    single-modality registration.

    Args:
        fixed: Mapping of modality name to fixed reference volume. The first key is
            the primary modality.
        moving: Mapping of modality name to moving volume. Must have the same keys
            as ``fixed``.
        weights: Per-modality weights for the deformable stage, normalised relative
            to the primary modality. Defaults to equal weighting.
        mask: Optional mask for the primary fixed image (Affine stage only).
        moving_mask: Optional mask for the primary moving image (Affine stage only).

    Returns:
        A tuple of a warped volumes dict (modality name : InMemoryVolumeResource)
        and a :class:`TransformResource` mapping moving space to fixed space.

    """
    if set(fixed.keys()) != set(moving.keys()):
        error_message = "fixed and moving must have the same modality keys."
        raise ValueError(error_message)

    modalities = list(fixed.keys())
    if len(modalities) < 2:
        error_message = (
            "register_volumes_multimetric requires at least 2 modalities. "
            "Use register_volumes for single-modality registration."
        )
        raise ValueError(error_message)
    primary_mod = modalities[0]

    # Load and validate all volumes
    ants_fixed: dict[str, ants.ANTsImage] = {}
    ants_moving: dict[str, ants.ANTsImage] = {}
    for m in modalities:
        fixed_loaded = fixed[m].load()
        moving_loaded = moving[m].load()
        if fixed_loaded.get_array().ndim > 3 or moving_loaded.get_array().ndim > 3:
            error_message = "Input volume dimensions must be 2D or 3D."
            raise ValueError(error_message)
        ants_fixed[m] = fixed_loaded.to_ants_image()
        ants_moving[m] = moving_loaded.to_ants_image()

    ants_mask = mask.load().to_ants_image() if mask is not None else None
    ants_moving_mask = (
        moving_mask.load().to_ants_image() if moving_mask is not None else None
    )

    # Normalise weights relative to the primary modality
    if weights is None:
        weights = dict.fromkeys(modalities, 1.0)
    norm_weights = {m: weights[m] / weights[primary_mod] for m in modalities}

    # Step 1: Affine registration on primary modality
    affine_result = ants.registration(
        fixed=ants_fixed[primary_mod],
        moving=ants_moving[primary_mod],
        mask=ants_mask,
        moving_mask=ants_moving_mask,
        type_of_transform="Affine",
    )
    affine_path: str = affine_result["fwdtransforms"][-1]

    # Step 2: SyNOnly deformable registration with multivariate_extras
    multivariate_metrics = [
        ["mattes", ants_fixed[m], ants_moving[m], norm_weights[m], 1]
        for m in modalities[1:]
    ]
    deformable_result = ants.registration(
        fixed=ants_fixed[primary_mod],
        moving=ants_moving[primary_mod],
        multivariate_extras=multivariate_metrics,
        type_of_transform="SyNOnly",
        initial_transform=affine_path,
    )
    warp_path: str = deformable_result["fwdtransforms"][0]

    # Combine affine + warp into a TransformResource (same path layout as SyN)
    transform = TransformResource(
        _ants_fwd_paths=[warp_path, affine_path],
        _ants_inv_paths=[affine_path] + deformable_result["invtransforms"],
    )

    # Warp all modalities using the combined transform
    warped: dict[str, InMemoryVolumeResource] = {
        primary_mod: InMemoryVolumeResource.from_ants_image(
            deformable_result["warpedmovout"]
        )
    }
    for m in modalities[1:]:
        warped_ants = ants.apply_transforms(
            fixed=ants_fixed[m],
            moving=ants_moving[m],
            transformlist=[warp_path, affine_path],
            whichtoinvert=[False, False],
        )
        warped[m] = InMemoryVolumeResource.from_ants_image(warped_ants)

    return warped, transform


@cacheable
def register_dwi_to_structural(
    dwi: Dwi,
    structural: StructuralImage,
    type_of_transform: str = "Rigid",
    dwi_mask: VolumeResource | None = None,
    structural_mask: VolumeResource | None = None,
) -> TransformResource:
    """Register a DWI (mean b0) to a structural (T1) image.

    Convenience wrapper around :func:`register_volumes`. The returned
    :class:`TransformResource` maps DWI space → T1 space. To warp T1-derived
    labels back into DWI space call
    ``transform.apply(..., invert=True, interpolation="genericLabel")``.
    See :meth:`TransformResource.apply` for details.

    Args:
        dwi: The DWI to register. The mean b0 is used as the moving image.
        structural: The structural image used as the fixed reference.
        type_of_transform: The transformation model (e.g., "Rigid", "Affine", "SyN").
        dwi_mask: Optional brain mask in DWI space (used as the moving mask).
        structural_mask: Optional brain mask in structural space (used as the fixed mask).

    Returns:
        A :class:`TransformResource` mapping DWI space → structural space.
    """
    _, transform = register_volumes(
        fixed=structural.volume,
        moving=dwi.compute_mean_b0(),
        type_of_transform=type_of_transform,
        mask=structural_mask,
        moving_mask=dwi_mask,
    )
    return transform
